name: Code Coverage

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Generate coverage with JaCoCo
        run: mvn -V --color always -ntp clean verify -Pci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.2.0
        with:
          file: 'target/site/jacoco/jacoco.xml'
          disable_search: true
          token: ${{secrets.CODECOV_TOKEN}}
